language: erlang
before_script:
- make get-lfetool
script:
- make check
notifications:
  recipients:
  - quasiquoting@gmail.com
otp_release:
- 18.1
- 17.5
- 17.3
before_install:
- openssl aes-256-cbc -K $encrypted_752b3d8e11c5_key -iv $encrypted_752b3d8e11c5_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
